-- CreateTable
CREATE TABLE "Produtos" (
    "IDPRODUTO" SERIAL NOT NULL,
    "DESCRICAO" VARCHAR(50) NOT NULL,
    "ATIVO" CHAR(1),
    "IDUNIDADE" INTEGER NOT NULL,
    "GTIN" VARCHAR(13) NOT NULL,
    "CODIGOINTERNO" VARCHAR(20) NOT NULL,
    "IDGRUPO" INTEGER NOT NULL,
    "PESADO" BOOLEAN NOT NULL DEFAULT false,
    "PRECO_CUSTO" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "MARGEM" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "PRECO_VENDA" DECIMAL(65,30) NOT NULL,
    "ESTO_MIN" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "ESTO_MAX" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "NCM" CHAR(8) NOT NULL,
    "CEST" CHAR(7) NOT NULL,
    "ORIGEM" VARCHAR(1) NOT NULL,
    "CSTIPI" VARCHAR(2) NOT NULL,
    "CSTICMS" VARCHAR(2) NOT NULL,
    "CSTPIS" VARCHAR(2) NOT NULL,
    "CSTCOFINS" VARCHAR(2) NOT NULL,
    "CSOSN" VARCHAR(3) NOT NULL,
    "SERIADO" BOOLEAN NOT NULL DEFAULT false,
    "ICMS" DECIMAL(65,30) NOT NULL,
    "IPI" DECIMAL(65,30) NOT NULL,
    "PIS" DECIMAL(65,30) NOT NULL,
    "COFINS" DECIMAL(65,30) NOT NULL,
    "FRETE" DECIMAL(65,30) NOT NULL,
    "DATA_CADASTRO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CFOP" VARCHAR(4) NOT NULL,
    "CFOP_FORA" VARCHAR(4) NOT NULL,
    "LOTE" VARCHAR(20),
    "PESO_BRUTO" DECIMAL(65,30),
    "PESO_LIQUIDO" DECIMAL(65,30),
    "OBSERVACAO" TEXT,
    "CODIGOPROD_FORNECEDOR" VARCHAR(50),

    CONSTRAINT "Produtos_pkey" PRIMARY KEY ("IDPRODUTO")
);

-- CreateTable
CREATE TABLE "Unidades" (
    "IDUNIDADE" SERIAL NOT NULL,
    "DESCRICAO" CHAR(3) NOT NULL,
    "ATIVO" CHAR(1),

    CONSTRAINT "Unidades_pkey" PRIMARY KEY ("IDUNIDADE")
);

-- CreateTable
CREATE TABLE "NCM" (
    "NCM" CHAR(8) NOT NULL,
    "CEST" CHAR(7),
    "DESCRICAO" VARCHAR(250),

    CONSTRAINT "NCM_pkey" PRIMARY KEY ("NCM")
);

-- AddForeignKey
ALTER TABLE "Produtos" ADD CONSTRAINT "Produtos_IDGRUPO_fkey" FOREIGN KEY ("IDGRUPO") REFERENCES "Grupos"("IDGRUPO") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Produtos" ADD CONSTRAINT "Produtos_IDUNIDADE_fkey" FOREIGN KEY ("IDUNIDADE") REFERENCES "Unidades"("IDUNIDADE") ON DELETE RESTRICT ON UPDATE CASCADE;
