-- AlterTable
ALTER TABLE "TBUTIL001" ADD COLUMN     "COFINS" DECIMAL(65,30) DEFAULT 0,
ADD COLUMN     "PIS" DECIMAL(65,30) DEFAULT 0,
ADD COLUMN     "SIMPLES" DECIMAL(65,30) DEFAULT 0;

-- CreateTable
CREATE TABLE "TBAGEN001" (
    "IDAGENDA" TEXT NOT NULL,
    "IDCLIENTE" INTEGER NOT NULL,
    "IDUSUARIO" TEXT NOT NULL,
    "DATAINICIO" TIMESTAMP(3) NOT NULL,
    "DATAFINAL" TIMESTAMP(3) NOT NULL,
    "TITULO" VARCHAR(100) NOT NULL,

    CONSTRAINT "TBAGEN001_pkey" PRIMARY KEY ("IDAGENDA")
);

-- AddForeignKey
ALTER TABLE "TBAGEN001" ADD CONSTRAINT "TBAGEN001_IDCLIENTE_fkey" FOREIGN KEY ("IDCLIENTE") REFERENCES "TBCLIE001"("IDCLIENTE") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "TBAGEN001" ADD CONSTRAINT "TBAGEN001_IDUSUARIO_fkey" FOREIGN KEY ("IDUSUARIO") REFERENCES "TBUTIL002"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
