-- CreateTable
CREATE TABLE "TBUTIL001" (
    "ID" TEXT NOT NULL,
    "RAZAO" VARCHAR(150) NOT NULL,
    "FANTASIA" VARCHAR(120) NOT NULL,
    "SIGLA" VARCHAR(5),
    "CNPJ" VARCHAR(14) NOT NULL,
    "IE" VARCHAR(14) NOT NULL,
    "IM" VARCHAR(20),
    "CNAE" VARCHAR(20) NOT NULL,
    "CEP" CHAR(8) NOT NULL,
    "ENDERECO" VARCHAR(150) NOT NULL,
    "NUM" VARCHAR(10) NOT NULL,
    "COMPLEMENTO" VARCHAR(50) NOT NULL,
    "BAIRRO" VARCHAR(100) NOT NULL,
    "CIDADE_IBGE" CHAR(7) NOT NULL,
    "CIDADE" VARCHAR(100) NOT NULL,
    "CODUF" CHAR(2) NOT NULL,
    "UF" CHAR(2) NOT NULL,
    "PAIS" VARCHAR(50) NOT NULL,
    "TELEFONE1" VARCHAR(13) NOT NULL,
    "TELEFONE2" VARCHAR(13),
    "TELEFONE3" VARCHAR(13),
    "EMAIL" VARCHAR(250) NOT NULL,
    "SITE" VARCHAR(250),
    "CONTATO" VARCHAR(80),
    "REGIME" CHAR(2) NOT NULL,

    CONSTRAINT "TBUTIL001_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "TBUTIL002" (
    "ID" TEXT NOT NULL,
    "NOME" VARCHAR(100) NOT NULL,
    "EMAIL" VARCHAR(100) NOT NULL,
    "SENHA" TEXT NOT NULL,
    "SETOR" TEXT NOT NULL,
    "ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "EMPRESA" TEXT NOT NULL,
    "TIPO" CHAR(2) NOT NULL,

    CONSTRAINT "TBUTIL002_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "TBCLI001" (
    "IDCLIENTE" SERIAL NOT NULL,
    "RAZAONOME" VARCHAR(120) NOT NULL,
    "FANTASIASOBRENOME" VARCHAR(100) NOT NULL,
    "SIGLA" VARCHAR(3),
    "CPFCNPJ" VARCHAR(14) NOT NULL,
    "RGIE" VARCHAR(14) NOT NULL,
    "CEP" CHAR(8),
    "ENDERECO" VARCHAR(150),
    "NUM" VARCHAR(10),
    "COMPLEMENTO" VARCHAR(50),
    "BAIRRO" VARCHAR(100),
    "CIDADE_IBGE" CHAR(7),
    "CIDADE" VARCHAR(100),
    "CODUF" CHAR(2),
    "UF" CHAR(2),
    "PAIS" VARCHAR(50),
    "CONTATO" VARCHAR(80),
    "TELEFONE1" VARCHAR(13) NOT NULL,
    "TELEFONE2" VARCHAR(13),
    "FORMAPAG" TEXT,
    "EMAIL" VARCHAR(250),
    "SITE" VARCHAR(250),
    "TRANSPORTADORA" TEXT,
    "REGIAO" TEXT,
    "VENDEDOR" TEXT,
    "TIPOCONTRIB" CHAR(2),
    "BLOQUEARCREDITO" CHAR(1),
    "DATAPROTESTO" TIMESTAMP(3),
    "LIMITECREDITO" DECIMAL(65,30) DEFAULT 0,
    "RAMOATIVIDADE" TEXT,
    "DATANASC" TIMESTAMP(3),
    "OBSERVACAO" TEXT,
    "DATACAD" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USERCAD" TEXT NOT NULL,
    "DATAALT" TIMESTAMP(3),
    "USERALT" TEXT,
    "EMPRESA" TEXT NOT NULL,
    "ATIVO" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TBCLI001_pkey" PRIMARY KEY ("IDCLIENTE")
);

-- CreateTable
CREATE TABLE "TBCAD001" (
    "IDENDERECO" TEXT NOT NULL,
    "IDCLIENTE" INTEGER,
    "TIPO" CHAR(1) NOT NULL,
    "ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "ENDERECO" VARCHAR(150) NOT NULL,
    "NUM" VARCHAR(10) NOT NULL,
    "COMPLEMENTO" VARCHAR(50) NOT NULL,
    "REFERENCIA" VARCHAR(50) NOT NULL,
    "BAIRRO" VARCHAR(100) NOT NULL,
    "CIDADE_IBGE" CHAR(7) NOT NULL,
    "CIDADE" VARCHAR(100) NOT NULL,
    "CODUF" CHAR(2) NOT NULL,
    "UF" CHAR(2) NOT NULL,
    "PAIS" VARCHAR(50) NOT NULL,

    CONSTRAINT "TBCAD001_pkey" PRIMARY KEY ("IDENDERECO")
);

-- CreateTable
CREATE TABLE "TBUTIL004" (
    "IDTELEFONE" TEXT NOT NULL,
    "IDCLIENTE" INTEGER,
    "TIPO" CHAR(1) NOT NULL,
    "NUMERO" VARCHAR(10),

    CONSTRAINT "TBUTIL004_pkey" PRIMARY KEY ("IDTELEFONE")
);

-- CreateIndex
CREATE UNIQUE INDEX "TBUTIL002_EMAIL_key" ON "TBUTIL002"("EMAIL");

-- AddForeignKey
ALTER TABLE "TBUTIL002" ADD CONSTRAINT "TBUTIL002_EMPRESA_fkey" FOREIGN KEY ("EMPRESA") REFERENCES "TBUTIL001"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBCLI001" ADD CONSTRAINT "TBCLI001_EMPRESA_fkey" FOREIGN KEY ("EMPRESA") REFERENCES "TBUTIL001"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBCAD001" ADD CONSTRAINT "TBCAD001_IDCLIENTE_fkey" FOREIGN KEY ("IDCLIENTE") REFERENCES "TBCLI001"("IDCLIENTE") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "TBUTIL004" ADD CONSTRAINT "TBUTIL004_IDCLIENTE_fkey" FOREIGN KEY ("IDCLIENTE") REFERENCES "TBCLI001"("IDCLIENTE") ON DELETE NO ACTION ON UPDATE NO ACTION;
